name: DocSearch Crawling using GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  crawl-the-webos-ose-website:
    runs-on: ubuntu-latest
    steps:
      - name: send dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: lge-swpbt/docsearch
          event-type: docsearch-crawling